# Generated by Django 4.2.3 on 2023-07-29 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_group_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to='student.group'),
        ),
    ]
